name: Build Kvm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Clone Kvm
      run: |
        git clone https://github.com/LGBT-CN/Kvm KvmC
        cd KvmC
        dotnet restore
        dotnet build --no-restore --configuration Release
    - name: Copy Data
      run: |
        cp -rf kvm/* KvmC/Kvm.ConsoleApp/bin/Release/net5.0/
        mkdir -p KvmC/Kvm.ConsoleApp/bin/Release/net5.0/out/page
    - name: Compile Kvm
      run: |
        cd KvmC/Kvm.ConsoleApp/bin/Release/net5.0/
        dotnet ./Kvm.ConsoleApp.dll
    - name: Combine files
      run: |
        mv KvmC/Kvm.ConsoleApp/bin/Release/net5.0/out/* ./
    - name: Clean Kvm
      run: |
        rm -rf kvm
        rm -rf KvmC
    - name: Commit to Pages
      run: |
        git checkout gh-page
        git config user.name KevinZonda
        git config user.email 33132228+KevinZonda@users.noreply.github.com
        git add .
        git commit -m "S.C.: `date "+%Y-%m-%d %H:%M:%S UTC%:z"`" || true
        git push
    # - name: Upload compiled files
    #   uses: actions/upload-artifact@v2.2.3
    #   with:
    #     path: ./