name: Build Kvm

on:
  push:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build Kvm
      run: |
        git clone https://github.com/LGBT-CN/Kvm KvmC
        cd KvmC
        dotnet restore
        dotnet build --no-restore --configuration Release
    - name: Copy Data
      run: |
        cp -rf kvm/* KvmC/Kvm.ConsoleApp/bin/Release/net5.0/
        mkdir -p KvmC/Kvm.ConsoleApp/bin/Release/net5.0/out/page
    - name: Compile .kvm files
      run: |
        cd KvmC/Kvm.ConsoleApp/bin/Release/net5.0/
        dotnet ./Kvm.ConsoleApp.dll
    - name: Combine files
      run: |
        mv static KvmC/Kvm.ConsoleApp/bin/Release/net5.0/out/

    - name: Commit to Pages
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: KvmC/Kvm.ConsoleApp/bin/Release/net5.0/out
        clean: true
    # - name: Upload compiled files
    #   uses: actions/upload-artifact@v2.2.3
    #   with:
    #     path: ./
